---
small:
  - 1
  - 2
  - 10
  - jobs:
    - debian_nfs_server
    - syslog_aggregator
    - collector
    - ccdb
    - uaa
    - uaadb
    - vcap_redis
    - login
    - health_manager
    - health_monitor
    - dashboard
    - cloud_controller
    - opentsdb
    - zkp
    - nats
    - hbase_master
    - hbase_slave
    - LB
middle:
  - 1
  - 2
  - 10
  - jobs:
    - router
large:
  - 1
  - 2
  - 10
  - jobs:
    - router
    - dea
    - ESBgateway
    - ESBnats
    - ESB
    - WSO2
